---
- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Ensure sysadmin utility packages are installed.
  ansible.builtin.package:
    state: present
    name: "{{ sysadmin_packages }}"

- name: Ensure custom sysadmin utility packages are installed.
  ansible.builtin.package:
    state: present
    name: "{{ sysadmin_packages_custom }}"
  when: sysadmin_packages_custom | length > 0

- name: Generate ed25519 SSH host key
  ansible.builtin.command:
    cmd: ssh-keygen -A
    creates: /etc/ssh/ssh_host_ed25519_key

- name: Prefer ed25519 HostKeys in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: 'HostKey /etc/ssh/ssh_host_ed25519_key'
    line: 'HostKey /etc/ssh/ssh_host_ed25519_key'
    state: present
  notify: restart ssh